name = "multiply-api"
main = "src/index.ts"
compatibility_date = "2026-05-13"

[[d1_databases]]
binding = "DB"
database_name = "multiply-champion-db"
database_id = "2e11a09a-4563-46aa-b191-efaf6a50aaef"
